name: Daily TALT Update

permissions:
  contents: write
  
on:
  schedule:
    - cron: "0 17 * * *"  # runs every day at 17:00 UTC, which is 6am in NZ winter, 5am in NZ summer
  workflow_dispatch:      # allows manual runs

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Set up R 
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3.1"

      # cache packages
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-packages-${{ hashFiles('DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-packages-

      # Install dependencies
      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            tidyverse
            readxl
            Microsoft365R

      # Set up OneDrive token
      - name: Set up OneDrive token
        run: |
          echo "${{ secrets.ONEDRIVE_TOKEN_BASE64 }}" | base64 --decode > token_onedrive.rds

      # Run R script
      - name: Run download and processing script
        run: Rscript scripts/workflow/03_process_talt_data.R

      - name: List downloaded files
        run: ls -lh data/talt_cyano/
       

      # Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git status
          git add -A
          git commit -m "Daily data update $(TZ='Pacific/Auckland' date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
