name: Trigger processing of BOPRC cyano data when file is added or modified

permissions:
  contents: write

on:
  push:
    paths:
      - "data/boprc_cyano/og_excel_files/**"

jobs:
  run-rscript:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.5.0"

      - name: Check R version
        run: Rscript -e 'R.version.string'          

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            tidyverse
            readxl
            tidyr

      - name: Debug - show R script content
        run: cat scripts/workflow/01_process_boprc_data.R

      - name: Run processing script
        run: Rscript scripts/workflow/01_process_boprc_data.R

      - name: Commit and push changes
        run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "github-actions[bot]@users.noreply.github.com"
         git add -A
         git commit -m "Update processed BOPRC cyano dataset [skip ci]" || echo "No changes to commit"
         git pull --rebase origin main
         git push
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
