name: Trigger processing of BOPRC cyano data when file is added or modified

on:
  push:
    paths:
      - "data/boprc_cyano/og_excel_files/**"

jobs:
  run-rscript:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3.3"

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            tidyverse
            readxl
            tidyr

      - name: Debug - show R script content
        run: cat scripts/workflow/01_process_boprc_data.R

      - name: Run processing script
        run: Rscript scripts/workflow/01_process_boprc_data.R

      - name: Commit and push processed data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/boprc_cyano/boprc_cyano_latest.csv
          # only commit if there are changes
          git diff-index --quiet HEAD || git commit -m "Update processed BOPRC cyano dataset [skip ci]"
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main
